// Copyright © 2026 baocommunity — licenced under AGPL-3.0 (see LICENSE.txt).

/**
 * @bao/frost-court — shared BAO Court / FROST threshold-oracle logic.
 */

export type {
  StakeCommitment,
  JurorProfile,
  SelectedJuror,
  FrostAttestation,
  DkgRecord,
  DisputeCase,
  AppealTimings,
  AppealPhase,
  JurorVote,
  JurorSessionState,
  EncryptedVssShare,
  DkgComplaint,
  DkgComplaintDefense,
  DkgVerificationFailure,
  EncryptedShareBackup,
  RefreshCommitment,
  EncryptedRefreshShare,
  IndependentDkgState,
  IndependentSigningState,
} from './types';

export {
  randomHex32,
  randomScalar,
  scalarToHex,
  deriveXOnlyPubkey,
  buildAttestationMessage,
  aggregatePublicNonce,
  verifyFinalSignature,
  verifySchnorr,
  createProofOfKnowledge,
  verifyProofOfKnowledge,
  frost,
} from './crypto';
export type { PublicNonce, DkgProofOfKnowledge } from './crypto';

export {
  COURT_SESSION_VERSION,
  COURT_SESSION_DOMAIN,
  COURT_ENVIRONMENTS,
  COURT_CRYPTO_SUITES,
  CourtSessionValidationError,
  assertCourtSessionParameters,
  encodeCourtSessionParameters,
  hashCourtSessionParameters,
  getCourtSessionParticipant,
  assertCourtParticipantBinding,
  type CourtEnvironment,
  type CourtCryptoSuite,
  type CourtParticipantRole,
  type CourtSessionParticipant,
  type CourtSessionParameters,
  type CourtSessionValidationCode,
} from './courtSession';

export {
  CourtProtocolEventError,
  bindCourtProtocolEvent,
  parseCourtProtocolEvent,
  classifyCourtProtocolEvent,
  parseLegacyCourtEventForHistory,
  parseBoundDkgCommitmentEvent,
  parseBoundVoteCommitEvent,
  parseBoundVoteRevealEvent,
  parseBoundFrostCommitEvent,
  parseBoundFrostRevealEvent,
  type CourtProtocolEventClassification,
  type CourtProtocolEventErrorCode,
  type CourtProtocolBinding,
  type ParsedCourtProtocolEvent,
  type ParsedLegacyCourtEvent,
  type ParsedBoundDkgCommitment,
  type ParsedBoundVoteCommit,
  type ParsedBoundVoteReveal,
  type ParsedBoundFrostCommit,
  type ParsedBoundFrostReveal,
} from './courtProtocolEvents';

export {
  CourtDkgTransitionError,
  createCourtDkgMachine,
  reduceCourtDkgMachine,
  type CourtDkgPhase,
  type CourtDkgFailurePhase,
  type CourtDkgFailure,
  type CourtDkgMachineState,
  type CourtDkgMachineEvent,
} from './courtDkgMachine';

export {
  COURT_VOTE_COMMIT_DOMAIN,
  COURT_VERDICT_DOMAIN,
  CourtVoteTransitionError,
  createCourtVoteMachine,
  hashCourtVerdict,
  hashCourtVoteCommit,
  reduceCourtVoteMachine,
  type CourtVotePhase,
  type CourtVoteFailure,
  type CourtVoteCommitRecord,
  type CourtVoteRevealRecord,
  type CourtVerdict,
  type CourtVoteMachineState,
  type CourtVoteMachineEvent,
} from './courtVoteMachine';

export {
  COURT_SIGNING_SESSION_DOMAIN,
  CourtSigningTransitionError,
  createCourtSigningMachine,
  hashCourtSigningSession,
  reduceCourtSigningMachine,
  type CourtSigningPhase,
  type CourtSigningFailurePhase,
  type CourtSigningFailure,
  type CourtSigningCommitmentRecord,
  type CourtSigningPartialRecord,
  type CourtSigningMachineState,
  type CourtSigningMachineEvent,
} from './courtSigningMachine';

export {
  PedersenDkgAdapter,
  generateFrostKeys,
  evaluatePoly,
  evaluateCommitments,
  evaluateRefreshCommitments,
  generateRefreshShares,
  mergeRefreshCommitments,
  modN,
  pointToXOnlyHex,
  verifyVssShare,
  verifyRefreshShare,
  combineShares,
  type DkgAdapter,
  type KeygenParams,
  type KeygenResult,
  type RefreshParams,
  type RefreshResult,
  type PedersenDkgOptions,
  type ParticipantState,
} from './dkg';

export {
  createCommitments,
  createCommitment,
  createRevealsAndPartialSigs,
  createRevealAndPartialSig,
  aggregateAttestation,
  runNormalSigningRound,
  InMemoryNonceGuard,
  LocalStorageNonceGuard,
  createDefaultNonceGuard,
  type SigningCommitment,
  type SigningReveal,
  type SigningRoundParams,
  type NonceGuard,
} from './signing';

export {
  hashCommit,
  tallyVotes,
  deriveDisputeGroupPubkey,
  runDisputeOverrideSigning,
  type TallyResult,
  type DisputeSigningParams,
} from './dispute';

export {
  BAO_COURT_DISPUTE_KIND,
  BAO_COURT_JUROR_CANDIDACY_KIND,
  BAO_COURT_SELECTION_KIND,
  BAO_COURT_DKG_COMMITMENT_KIND,
  BAO_COURT_VOTE_COMMIT_KIND,
  BAO_COURT_VOTE_REVEAL_KIND,
  BAO_COURT_FROST_COMMIT_KIND,
  BAO_COURT_FROST_REVEAL_KIND,
  BAO_COURT_ATTESTATION_KIND,
  buildDisputeEvent,
  buildJurorCandidacyEvent,
  buildSelectionEvent,
  buildDkgCommitmentEvent,
  buildVoteCommitEvent,
  buildVoteRevealEvent,
  buildFrostCommitEvent,
  buildFrostRevealEvent,
  buildDisputeAttestationEvent,
  buildAttestationEvent,
  parseAttestationEvent,
  parseJurorCandidacyEvent,
  parseSelectionEvent,
  parseDkgCommitmentEvent,
  parseVoteCommitEvent,
  parseVoteRevealEvent,
  parseFrostCommitEvent,
  parseFrostRevealEvent,
  validateSelectionEvent,
  type SelectedJurorEntry,
  type SelectionValidationResult,
} from './events';

export {
  wrapProtocolEvent,
  unwrapProtocolEvent,
  unwrapProtocolEvents,
  getPubkeyFromSeckey,
} from './nip59';

export {
  Nip44SignerCrypto,
  SeckeyCourtSigner,
  wrapProtocolEventWithSigner,
  unwrapProtocolEventWithSigner,
  unwrapProtocolEventsWithSigner,
  generateCourtSeckeyHex,
  type CourtEventSigner,
} from './courtSigner';

export {
  COURT_CAPABILITY_VERSION,
  COURT_SIGNER_CAPABILITY_DOMAIN,
  COURT_CEREMONY_PHASES,
  COURT_CAPABILITY_PHASE_SCOPES,
  CourtCapabilityError,
  assertCourtSignerCapability,
  createCourtCapability,
  encodeCourtCapability,
  hashCourtCapability,
  assertCourtCapabilityAction,
  describeCourtCapability,
  type CourtCeremonyPhase,
  type CourtCapabilityPhaseScope,
  type CourtSignerCapability,
  type CourtCapabilityAction,
  type CourtCapabilityErrorCode,
} from './courtNip46';

export {
  COURT_OUTBOX_MESSAGE_DOMAIN,
  COURT_DELIVERY_ACK_KIND,
  COURT_OUTBOX_SNAPSHOT_VERSION,
  COURT_OUTBOX_DEFAULT_PARAMS,
  CourtOutboxError,
  CourtOutbox,
  createCourtOutbox,
  hashCourtOutboxMessage,
  type CourtOutboxEntryStatus,
  type CourtOutboxErrorCode,
  type CourtOutboxRetryParams,
  type CourtOutboxParams,
  type OutboxStorage,
  type CourtOutboxWrapTemplate,
  type CourtOutboxEnqueueInput,
  type CourtOutboxEntry,
  type CourtOutboxSnapshot,
} from './courtOutbox';

export {
  COURT_KEEPER_DESIGNATION_DOMAIN,
  COURT_KEEPER_COMMITMENT_DOMAIN,
  COURT_KEEPER_STREAM_DOMAIN,
  CourtKeeperError,
  keeperCandidateOrder,
  designateKeepers,
  assertKeeperDesignation,
  encodeKeeperDesignation,
  hashKeeperDesignation,
  commitKeeperSecret,
  encodeKeeperCommitment,
  hashKeeperCommitment,
  assertKeeperCommitmentForDesignation,
  hashKeeperSecret,
  verifyKeeperReveal,
  type CourtKeeperBranch,
  type CourtKeeperErrorCode,
  type CourtKeeperExclusions,
  type DesignateKeepersParams,
  type CourtKeeperPair,
  type CourtKeeperDesignation,
  type CourtKeeperCommitment,
} from './courtKeeper';

export {
  COURT_GIFT_WRAP_KIND,
  COURT_INBOX_SNAPSHOT_VERSION,
  COURT_WRAP_LOOKBACK_SECONDS,
  COURT_INBOX_PUBLIC_KINDS,
  CourtInboxError,
  CourtInbox,
  createCourtInbox,
  publishToGroup,
  readFromGroup,
  buildCourtSubscriptions,
  classifyInboundEvent,
  type CourtInboxErrorCode,
  type CourtRelayFilter,
  type CourtRelayConnection,
  type CourtRelayPublishResult,
  type CourtRelayPublishReport,
  type CourtGroupDelivery,
  type CourtSubscriptionParams,
  type CourtInboxRejectReason,
  type CourtInboxCategory,
  type CourtInboxClassification,
  type CourtInboxClassifyParams,
  type CourtInboxWrap,
  type CourtInboxRecord,
  type CourtInboxParams,
  type CourtInboxSnapshot,
  type CourtInboxMessage,
  type CourtInboxIngestResult,
} from './courtInbox';

export {
  COURT_HOST_KEY_BACKUP_VERSION,
  COURT_HOST_KEY_ATTESTATION_VERSION,
  COURT_HOST_KEY_BACKUP_DOMAIN,
  COURT_HOST_KEY_BACKUP_ENVELOPE_DOMAIN,
  COURT_HOST_KEY_ATTESTATION_DOMAIN,
  COURT_HOST_KEY_SUPERSESSION_DOMAIN,
  CourtHostKeyError,
  CourtHostKey,
  generateCourtHostKey,
  createCourtHostKeyBackup,
  restoreCourtHostKeyFromBackup,
  createCourtHostKeyAttestation,
  assertCourtHostKeyAttestation,
  encodeCourtHostKeyAttestation,
  hashCourtHostKeyAttestation,
  courtHostKeyAttestationTags,
  verifyCourtHostKeyAttestationEvent,
  assertRosterHostKeyBinding,
  assertCourtHostKeyChain,
  resolveCurrentCourtHostKeyAttestation,
  rotateCourtHostKey,
  buildCourtHostKeyBackupEvent,
  parseCourtHostKeyBackupEvent,
  type CourtHostKeyErrorCode,
  type CourtHostKeyBackupEnvelope,
  type CourtHostKeyAttestation,
  type RotateCourtHostKeyResult,
} from './courtHostKey';

export {
  COURT_RECOVERY_ENVELOPE_VERSION,
  COURT_RECOVERY_ENVELOPE_DOMAIN,
  COURT_RECOVERY_LEGACY_SUITE,
  COURT_RECOVERY_ENVELOPE_KIND,
  CourtRecoveryError,
  encodeCourtRecoveryPayloadV1,
  hashCourtRecoveryPayload,
  serializeCourtRecoveryPayloadV1,
  createCourtRecoveryEnvelope,
  restoreCourtRecovery,
  buildCourtRecoveryEnvelopeEvent,
  parseCourtRecoveryEnvelopeEvent,
  type CourtRecoveryErrorCode,
  type CourtRecoveryEnvelopeV1,
  type CourtRecoveryPayloadV1,
  type CourtRecoveryCertificateRef,
  type CourtRecoveredShare,
  type CourtRecoveredDkg,
} from './courtRecovery';

export {
  buildEncryptedShareEvent,
  buildDkgComplaintEvent,
  buildShareBackupEvent,
  buildRefreshCommitmentEvent,
  buildEncryptedRefreshShareEvent,
  parseEncryptedShareEvent,
  parseDkgComplaintEvent,
  parseShareBackupEvent,
  parseRefreshCommitmentEvent,
  parseEncryptedRefreshShareEvent,
  BAO_COURT_ENCRYPTED_SHARE_KIND as ENCRYPTED_SHARE_KIND,
  BAO_COURT_DKG_COMPLAINT_KIND as DKG_COMPLAINT_KIND,
  BAO_COURT_SHARE_BACKUP_KIND as SHARE_BACKUP_KIND,
  BAO_COURT_REFRESH_COMMITMENT_KIND as REFRESH_COMMITMENT_KIND,
  BAO_COURT_REFRESH_SHARE_KIND as REFRESH_SHARE_KIND,
} from './dkgMessages';

export {
  IndependentDkgSession,
  type IndependentDkgOptions,
} from './independentDkg';

export {
  Nip44SeckeyCrypto,
  type Nip44Crypto,
} from './nip44Crypto';

export {
  IndependentSigningSession,
  type IndependentSigningOptions,
  type IndependentSigningSnapshot,
  type SigningSnapshotCommitment,
  type SigningSnapshotReveal,
} from './independentSigning';

export {
  verifyBond,
  computeRequiredBond,
  createBaoMempoolVerifier,
  createEsploraVerifier,
  type UtxoInfo,
  type BondVerificationResult,
  type BondVerifier,
  type VerifyBondOptions,
} from './bondVerification';

export {
  deriveSelectionSeed,
  jurorRandomValue,
  quadraticPriority,
  filterEligibleJurors,
  selectJury,
  selectJuryWithBackups,
  verifyJurySelection,
  type SelectionParams,
  type JuryWithBackups,
} from './selection';

export {
  validateAttestationEvent,
  verifyRawSignature,
  type ValidationResult,
} from './validator';
